### ISSUE TITLE
【O01 / hotfix】末尾full gateで判明した標準APIとfixture契約の不整合を解消

### ISSUE THREAD

**Issue by KentaroMorishita** [KentaroMorishita/seseragi#577]
## Orchestration

- O01 #549; Impl #291; Promotion #546; contract #512 section 20.
- Found by collecting terminal #321 full gate, diagnostic candidate `514cd992` (runner PR #576).
- Append after existing hotfix #575; retain the implemented stack ancestry.

## Observed failures

- `seseragi-conformance::stdlib_parity::tests::covers_every_available_module_with_a_runtime_and_product_route`: actual 61 vs expected 60. #321 adds std/benchmark; retain complete runtime/product route validation.
- `seseragi-driver --test compile_module`: two tests still assume std/benchmark is unavailable. #321 implements that module; preserve available-module behavior and ordered unresolved-import diagnostics using genuinely unresolved imports.
- `seseragi-driver --test monoid_wrappers::numeric_wrappers_use_conditional_canonical_evidence`: the fixture uses `([]: Array<Sum<Int>>)`, now parsed against #298 List cons syntax. Verify the normative annotation contract and preserve empty Array Monoid evidence with valid source; do not weaken nominal identity checks.

## Handoff

Resolve these failures in Impl after #575, retain meaningful regression coverage, record focused test evidence and exact origin checkpoint. Promotion will test the complete new terminal once and publish only after all required checks pass. Further failures from the same collection may be added with exact evidence; no success claim for unexecuted checks.

## Implemented checkpoint

- Origin `fix/issue-577-terminal-contracts` @ `93f3be614c96b1502d2ba12743c0d5a4a4c8d036`, after #575. Includes merged runner/batch infrastructure from main `35b6a81d`.
- Fixed std/benchmark availability/parity tests and valid empty Array annotation fixture; retained negative unresolved import and nominal checks. Fixed benchmark-host optional properties under strict TypeScript. Regenerated Playground runtime registry through its canonical producer after the complete gate found missing benchmark exports.
- Full gate now runs every runtime/ts test instead of a partial enumerated list. Extension tests are already run by package; no duplicate invocation added.
- Focused evidence: 38 Rust tests passed (compile_module, monoid_wrappers, stdlib_parity); 10 benchmark runtime tests passed; runtime strict TypeScript passed; 6 Playground registry tests / 3814 assertions passed; 6 runner/workflow tests / 34 assertions passed. Full baseline runtime/extension supplement: 208 passed.
- Full terminal verification and release pending; worktree is retained for the next appended formatter hotfix.

## O01 batch promotion 完了 — 2026-09-09

- Canonical release: [v0.61.7](https://github.com/KentaroMorishita/seseragi/releases/tag/v0.61.7)、main/tag commit `4880790384333e50405cf350753b76fc3c5f2264`。native archives・checksums・各 platform VSIX・runtime・WASM の全15 assets を確認。
- [PR #582](https://github.com/KentaroMorishita/seseragi/pull/582) は ancestry-preserving merge 済み。#393 から #581 まで全19 checkpoint が main の祖先。
- 最終 checkpoint #581 `e41a649db8910bef79e578d7194b19f99310f3f3` の [公式 full preflight](https://github.com/KentaroMorishita/seseragi/actions/runs/34242185064) 成功。全独立検査を集約して最後まで実行し、失敗は #575 / #577 / #578 / #579 / #580 / #581 の Impl 末尾 hotfix で収束。
- [Publish preparation](https://github.com/KentaroMorishita/seseragi/actions/runs/34244592540) と PR CI 成功。tested candidate `3b5a51b9020ebdfcbbc60553d02282733c52bfeb` → published candidate `c935e8f0c5d31a7562f6086582108a8d7cdc6ad8` は official mechanical delta 検証済み。PR の追加差分は batch 全体を説明する CHANGELOG のみで、release contract/readiness を再検証。main tree は PR head `b04e701b4309752cef3f916ff25ab865b95e1d2d` と一致。
- [Canonical release workflow](https://github.com/KentaroMorishita/seseragi/actions/runs/34246032260) 全ジョブ成功。main source gate、Linux glibc baseline、各 OS の native/VSIX、downloaded native smoke、配布版 Web product E2E を含む。
- 本番 Playground と同期済み公式 CLI で array-index / char-literal / std-parity-portable（std/math含む）/ fallback-list-multimodule / Lesson 02 の同一5ケースを実行し、全て期待値と一致。WASM compile/analyze、LSP/formatter/reference を含む全体 gate も成功。
- main 上の `bun run dogfood:sync` / `bun run dogfood:check` 成功。CLI / standalone LSP / official extension / bundled LSP は全て 0.61.7 (darwin-arm64)、release commit `488079038433`。`release:readiness:check`: released。
- Verifier は現 coordinator と GitHub Actions。subagent spawn なし（spawn model / reasoning_effort は N/A、override なし）。local diagnostic と official terminal candidate の full gate、platform CI shard を使用し、祖先 leaf ごとの重複 full gate は省略する #512 section 20 に従った。
- 所有 implementation / verification / promotion worktree と test server/browser/process は cleanup 済み。`git worktree list` は clean な main のみ。checkpoint refs と `/tmp/o01-*` のログ・結果JSON・画像・生成差分は ancestry / 検証監査用に保持。shared Cargo target/cache は保持し、routine cargo clean は未実施。#547 の O01 cleanup debt は 0。
